FROM ubuntu:latest

ARG USERNAME=micheal_scran
ARG USER_UID=1000
ARG USER_GID=$USER_UID

ENV DEBIAN_FRONTEND=noninteractive

# installing base deps
RUN apt update && \
    apt install --no-install-recommends -y \
        ca-certificates \
        curl \
        build-essential \
        git \
        ssh \
        sudo 

# adding dev user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -ms /bin/bash $USERNAME \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# setting default user
USER $USERNAME


# installing go

RUN sudo apt install -y golang-go

RUN go install github.com/cosmtrek/air@latest  

RUN echo "alias air='~/go/bin/air'" >> ~/.bashrc
